// Generated by CoffeeScript 1.6.2
(function() {
  var FirmNewCtrl, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  FirmNewCtrl = (function(_super) {
    __extends(FirmNewCtrl, _super);

    function FirmNewCtrl() {
      _ref = FirmNewCtrl.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    FirmNewCtrl.prototype.events = {
      "singleTap a[data-action=save]": "onSave",
      "singleTap a[data-action=cancel]": "onCancel",
      "load #newFirm": "loadFirm",
      "unload #newFirm": "unloadFirm",
      "change #firDomain": "changeFirDomain"
    };

    FirmNewCtrl.prototype.elements = {
      "a[data-action=save]": "buttonSave",
      "a[data-action=cancel]": "buttonCancel",
      "#firName": "firName",
      "#firDomain": "firDomain",
      "#firServer": "firServer",
      "#firAddress": "firAddress",
      "#firCity": "firCity",
      "#firState": "firState",
      "#firCP": "firCP",
      "#firCountry": "firCountry",
      "#firResponName": "firResponName",
      "#firResponSurname": "firResponSurname",
      "#firResponEmail": "firResponEmail",
      "#firResponTelf1": "firResponTelf1",
      "#firBookingClient": "firBookingClient",
      "#firBilledModule": "firBilledModule",
      "#firTaskMulClients": "firTaskMulClients",
      "#firClassTasks": "firClassTasks",
      "#firGwtUsers": "firGwtUsers"
    };

    FirmNewCtrl.prototype.changeFirDomain = function(event) {
      var asyn, data, firDom, firm, firmDom, url;

      firm = __FacadeCore.Cache_get(appName + "firmNew");
      firDom = "";
      if (firm) {
        firDom = firm.firDomain;
      }
      if (this.firDomain.val().length > 0 && (firDom.length === 0 || (firDom.length > 0 && firDom !== this.firDomain.val()))) {
        asyn = __FacadeCore.Service_Settings_asyncFalse();
        url = "http://" + appHost + "/firm/admin/get";
        data = {
          domain: this.firDomain.val()
        };
        firmDom = $$.json(url, data);
        __FacadeCore.Service_Settings_async(asyn);
        if (firmDom) {
          this.firDomain[0].focus();
          Lungo.Notification.success(findLangTextElement("label.notification.existsDomain.title"), findLangTextElement("label.notification.existsDomain.text"), null, 3);
          return false;
        }
      }
      return true;
    };

    FirmNewCtrl.prototype.loadFirm = function(event) {
      var a, asyn, firm, i, objSelectMul, option, strTaskClass, taskClass, tasksClass, url, _i, _j, _len, _len1, _ref1, _results;

      firm = __FacadeCore.Cache_get(appName + "firmNew");
      asyn = __FacadeCore.Service_Settings_asyncFalse();
      url = "http://" + appHost + "/taskClass/operator/list";
      tasksClass = $$.json(url, null);
      tasksClass = Lungo.Core.orderByProperty(tasksClass, "tclName", "asc");
      __FacadeCore.Service_Settings_async(asyn);
      objSelectMul = Lungo.dom("#firm-form #firClassTasks");
      i = -1;
      for (_i = 0, _len = tasksClass.length; _i < _len; _i++) {
        taskClass = tasksClass[_i];
        i++;
        objSelectMul[0].options[i] = new Option(taskClass.tclName, taskClass.id);
      }
      if (firm) {
        this.firName.val(firm.firName);
        this.firDomain.val(firm.firDomain);
        this.firServer.val(firm.firServer);
        this.firAddress.val(firm.firAddress);
        this.firCity.val(firm.firCity);
        this.firState.val(firm.firState);
        this.firCP.val(firm.firCP);
        this.firCountry.val(firm.firCountry);
        this.firResponName.val(firm.firResponName);
        this.firResponSurname.val(firm.firResponSurname);
        this.firResponEmail.val(firm.firResponEmail);
        this.firResponTelf1.val(firm.firResponTelf1);
        this.firBookingClient[0].options.selectedIndex = firm.firBookingClient;
        this.firBilledModule[0].options.selectedIndex = firm.firBilledModule;
        this.firTaskMulClients[0].options.selectedIndex = firm.firTaskMulClients;
        this.firGwtUsers.val(firm.firGwtUsers.toString());
        strTaskClass = firm.firClassTasks.toString();
        a = strTaskClass.split(",");
        _ref1 = objSelectMul[0].options;
        _results = [];
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          option = _ref1[_j];
          if ((a.indexOf(option.value)) !== -1) {
            _results.push(option.selected = true);
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    };

    FirmNewCtrl.prototype.onSave = function(event) {
      var data, firm, i, objSelectMul, option, strFirClass, url, _i, _len, _ref1, _this;

      if (this.changeFirDomain(event)) {
        __FacadeCore.Cache_remove(appName + "elementSave");
        __FacadeCore.Cache_remove(appName + "elementCancel");
        __FacadeCore.Cache_set(appName + "elementSave", this.buttonSave.html());
        __FacadeCore.Cache_set(appName + "elementCancel", this.buttonCancel.html());
        Lungo.Element.loading(this.buttonSave.selector, "black");
        Lungo.Element.loading(this.buttonCancel.selector, "black");
        url = "http://" + appHost + "/firm/admin/new";
        data = {
          firName: this.firName.val(),
          firDomain: this.firDomain.val(),
          firServer: this.firServer.val(),
          firAddress: this.firAddress.val(),
          firCity: this.firCity.val(),
          firState: this.firState.val(),
          firCP: this.firCP.val(),
          firCountry: this.firCountry.val(),
          firResponName: this.firResponName.val(),
          firResponSurname: this.firResponSurname.val(),
          firResponEmail: this.firResponEmail.val(),
          firResponTelf1: this.firResponTelf1.val(),
          firBookingClient: this.firBookingClient.val(),
          firBilledModule: this.firBilledModule.val(),
          firTaskMulClients: this.firTaskMulClients.val(),
          firGwtUsers: this.firGwtUsers.val()
        };
        objSelectMul = Lungo.dom("#firm-form #firClassTasks");
        strFirClass = "";
        i = 0;
        _ref1 = objSelectMul[0].options;
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          option = _ref1[_i];
          if (option.selected) {
            if (i > 0) {
              strFirClass += ",";
            }
            strFirClass += option.value;
            i++;
          }
        }
        data.firClassTasks = strFirClass;
        firm = __FacadeCore.Cache_get(appName + "firmNew");
        if (firm) {
          data.id = firm.firId;
        }
        _this = this;
        return $$.post(url, data, function(response) {
          return Lungo.Notification.success(findLangTextElement("label.notification.salvedData.title"), findLangTextElement("label.notification.salvedData.text"), null, 3, function(response) {
            __FacadeCore.Router_article("admin", "list-firm");
            AppAdmin.firmDomain = _this.firDomain.val();
            return _this.resetArticle();
          });
        });
      }
    };

    FirmNewCtrl.prototype.onCancel = function(event) {
      __FacadeCore.Cache_remove(appName + "elementSave");
      __FacadeCore.Cache_remove(appName + "elementCancel");
      __FacadeCore.Cache_set(appName + "elementSave", this.buttonSave.html());
      __FacadeCore.Cache_set(appName + "elementCancel", this.buttonCancel.html());
      Lungo.Element.loading(this.buttonSave.selector, "black");
      Lungo.Element.loading(this.buttonCancel.selector, "black");
      __FacadeCore.Router_article("admin", "list-firm");
      return this.resetArticle();
    };

    FirmNewCtrl.prototype.resetArticle = function() {
      this.buttonSave.html(__FacadeCore.Cache_get(appName + "elementSave"));
      this.buttonCancel.html(__FacadeCore.Cache_get(appName + "elementCancel"));
      this.firName.val("");
      this.firDomain.val("");
      this.firServer.val("");
      this.firAddress.val("");
      this.firCity.val("");
      this.firState.val("");
      this.firCP.val("");
      this.firCountry.val("");
      this.firResponName.val("");
      this.firResponSurname.val("");
      this.firResponEmail.val("");
      this.firResponTelf1.val("");
      this.firBookingClient.val("");
      this.firBilledModule.val("");
      this.firTaskMulClients.val("");
      return this.firGwtUsers.val("");
    };

    FirmNewCtrl.prototype.unloadFirm = function(event) {
      return __FacadeCore.Cache_remove(appName + "firmNew");
    };

    return FirmNewCtrl;

  })(Monocle.Controller);

  __Controller.FirmNew = new FirmNewCtrl("section#newFirm");

}).call(this);
