// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  __View.FirmListAdminView = (function(_super) {
    __extends(FirmListAdminView, _super);

    function FirmListAdminView() {
      _ref = FirmListAdminView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    FirmListAdminView.prototype.container = "section#admin article#list-firm ul";

    FirmListAdminView.prototype.template_url = "/web/templates/firmListAdmin.mustache";

    FirmListAdminView.prototype.events = {
      "singleTap li": "onSingleTap",
      "doubleTap li": "onDoubleTap"
    };

    FirmListAdminView.prototype.onSingleTap = function(event) {
      __FacadeCore.Cache_remove(appName + "firmNew");
      __FacadeCore.Cache_set(appName + "firmNew", this.model);
      AppAdmin.firmDomain = this.model.firDomain;
      return __FacadeCore.Router_section("newFirm");
    };

    FirmListAdminView.prototype.onDoubleTap = function(event) {
      if (__FacadeCore.isDoubleTap(event)) {
        return this.onEnabled(event);
      }
    };

    FirmListAdminView.prototype.onEnabled = function(event) {
      var dataAccept, dataCancel, dataConfirm, _this;

      _this = this;
      dataAccept = {
        icon: 'checkmark',
        label: 'Accept',
        callback: function() {
          return _this.onEnabledConfirm(event);
        }
      };
      dataCancel = {
        icon: 'checkmark',
        label: 'Cancel',
        callback: function() {
          return {};
        }
      };
      dataConfirm = {
        icon: 'user',
        title: findLangTextElement("label.notification.enabledFirm.title"),
        description: findLangTextElement("label.notification.enabledFirm.text"),
        accept: dataAccept,
        cancel: dataCancel
      };
      return Lungo.Notification.confirm(dataConfirm);
    };

    FirmListAdminView.prototype.onEnabledConfirm = function(event) {
      var data, url;

      url = "http://" + appHost + "/firm/admin/enabled";
      data = {
        id: this.model.firId
      };
      return $$.put(url, data, function() {
        return __Controller.FirmListAdmin.loadFirm(event);
      });
    };

    return FirmListAdminView;

  })(Monocle.View);

}).call(this);
